name: medical_app
description: "Медицинское приложение для анализа данных пациентов"
publish_to: 'none'

version: 1.0.3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP клиент для работы с API
  http: ^1.1.0
  
  # Управление состоянием
  provider: ^6.1.1
  
  # Локальное хранение данных
  shared_preferences: ^2.2.2
  
  # Навигация
  go_router: ^12.1.3
  
  # UI компоненты
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  
  # Работа с файлами
  file_picker: ^10.2.0
  
  # Уведомления (временно отключено из-за проблем совместимости)
  # flutter_local_notifications: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/images/
  
#  assets:
#    - assets/images/
#
#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/Roboto-Regular.ttf
#        - asset: assets/fonts/Roboto-Bold.ttf
#          weight: 700